/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';

const Balloon = React.forwardRef(({ ...props }, ref) => {
    const { nodes } = useGLTF('/StarBalloon-transformed.glb');

    return (
        <group 
            ref={ref} 
            {...props} 
            dispose={null} 
        >
            <mesh 
                geometry={nodes['Balloon_-_smoothed'].geometry} 
                scale={[props.scale, props.scale, props.scale]}
                onClick={props.handleClick}
            >
                { props.material }
            </mesh>
        </group>
    )
})

export default Balloon;

useGLTF.preload('/StarBalloon-transformed.glb')
